import { Opportunity } from './types';
export const demoOpportunities: Opportunity[] = [
  {id:'demo-google-india',title:'Software Engineer, New Grad',type:'JOB',organization:'Google',description:'Build scalable software used by billions of people. This role is based in Bengaluru.',field:'Software Engineering',country:'India',region:'Karnataka',city:'Bengaluru',latitude:12.9716,longitude:77.5946,workMode:'On-site',experienceRequired:'0–2 years',salary:'₹12,00,000–₹22,00,000',currency:'INR',eligibility:'Eligible graduates',deadline:'2026-10-18',applicationUrl:'https://careers.google.com/',sourceUrl:'https://careers.google.com/',sourceName:'Google Careers',verified:true},
  {id:'demo-noida-ai',title:'AI/ML Engineer',type:'JOB',organization:'Technology Company',description:'Work on production machine-learning systems and applied AI.',field:'AI / Machine Learning',country:'India',region:'Uttar Pradesh',city:'Noida',latitude:28.5355,longitude:77.3910,workMode:'On-site',experienceRequired:'0–2 years',salary:'₹8,00,000–₹16,00,000',currency:'INR',eligibility:'Engineering graduates',deadline:'2026-10-11',applicationUrl:'https://www.linkedin.com/jobs/',sourceUrl:'https://www.linkedin.com/jobs/',sourceName:'Demo source',verified:false},
  {id:'demo-microsoft-munich',title:'Software Engineering Intern',type:'INTERNSHIP',organization:'Microsoft',description:'Join an engineering team for a hands-on software development internship.',field:'Software Engineering',country:'Germany',region:'Bavaria',city:'Munich',latitude:48.1351,longitude:11.5820,workMode:'Hybrid',experienceRequired:'Students / 0–1 year',salary:'Competitive',currency:'EUR',eligibility:'University students',deadline:'2026-10-25',applicationUrl:'https://jobs.careers.microsoft.com/',sourceUrl:'https://jobs.careers.microsoft.com/',sourceName:'Microsoft Careers',verified:true},
  {id:'demo-nvidia-santaclara',title:'Machine Learning Intern',type:'INTERNSHIP',organization:'NVIDIA',description:'Research and prototype machine-learning solutions with an applied AI team.',field:'AI / Machine Learning',country:'United States',region:'California',city:'Santa Clara',latitude:37.3541,longitude:-121.9552,workMode:'On-site',experienceRequired:'Students / 0–1 year',salary:'Competitive',currency:'USD',eligibility:'University students',deadline:'2026-11-02',applicationUrl:'https://www.nvidia.com/en-us/about-nvidia/careers/',sourceUrl:'https://www.nvidia.com/en-us/about-nvidia/careers/',sourceName:'NVIDIA Careers',verified:true},
  {id:'demo-mext-japan',title:'Japanese Government Scholarship (MEXT)',type:'SCHOLARSHIP',organization:'Government of Japan',description:'Scholarship pathway for international students pursuing study in Japan.',field:'Higher Education',country:'Japan',city:null,region:null,latitude:36.2048,longitude:138.2529,workMode:'On-campus',experienceRequired:'Varies',salary:'Tuition + stipend',currency:'JPY',eligibility:'International students; eligibility varies by program',deadline:'2027-01-15',applicationUrl:'https://www.studyinjapan.go.jp/en/',sourceUrl:'https://www.studyinjapan.go.jp/en/',sourceName:'Study in Japan',verified:true},
  {id:'demo-daad-germany',title:'DAAD Scholarship Opportunities',type:'SCHOLARSHIP',organization:'DAAD',description:'Funding opportunities for international students and researchers studying in Germany.',field:'Higher Education',country:'Germany',city:null,region:null,latitude:51.1657,longitude:10.4515,workMode:'On-campus',experienceRequired:'Varies',salary:'Varies by program',currency:'EUR',eligibility:'International students; program-specific',deadline:'2027-02-01',applicationUrl:'https://www.daad.de/en/study-and-research-in-germany/scholarships/',sourceUrl:'https://www.daad.de/en/study-and-research-in-germany/scholarships/',sourceName:'DAAD',verified:true}
];
